import { ThemeTokens } from './tokensSchema';

export interface ThemePreset {
  id: string;
  name: string;
  tokens: ThemeTokens;
  settings?: {
    googleFonts?: boolean;
    fontAwesome?: boolean;
    animateCss?: boolean;
    heroIcons?: boolean;
  };
}

export const THEME_PRESETS: ThemePreset[] = [
  {
    id: 'preset-claro',
    name: 'Claro (Indigo)',
    tokens: {
      primary: '#6366f1',
      background: '#ffffff',
      foreground: '#111827',
      secondary: '#f1f5f9',
      accent: '#10b981',
      muted: '#f3f4f6',
      destructive: '#ef4444',
      border: '#e5e7eb',
      input: '#e5e7eb',
      ring: '#6366f1',
      card: '#ffffff',
      cardForeground: '#111827',
      popover: '#ffffff',
      popoverForeground: '#111827',
      radius: 8,
      fontFamily: "'Inter', system-ui, sans-serif",
      fontSizeBase: 16,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
      spacing: 4,
      headerHeight: 56,
      sidebarWidth: 240,
      footerHeight: 48,
      breakpointSm: 640,
      breakpointMd: 768,
      breakpointLg: 1024,
      breakpointXl: 1280,
      direction: 'ltr',
      datavizColor1: '#3b82f6',
      datavizColor2: '#ef4444',
      datavizColor3: '#10b981',
      datavizColor4: '#f97316',
      datavizColor5: '#8b5cf6',
      motion: 'full'
    },
    settings: { googleFonts: true, fontAwesome: false, animateCss: false, heroIcons: true }
  },
  {
    id: 'preset-minimalista',
    name: 'Minimalista (Emerald)',
    tokens: {
      primary: '#10b981',
      background: '#ffffff',
      foreground: '#0f172a',
      secondary: '#eef2f7',
      accent: '#06b6d4',
      muted: '#f3f4f6',
      destructive: '#dc2626',
      border: '#e5e7eb',
      input: '#e5e7eb',
      ring: '#10b981',
      card: '#ffffff',
      cardForeground: '#0f172a',
      popover: '#ffffff',
      popoverForeground: '#0f172a',
      radius: 10,
      fontFamily: "'Inter', system-ui, sans-serif",
      fontSizeBase: 16,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
      spacing: 4,
      headerHeight: 56,
      sidebarWidth: 248,
      footerHeight: 48,
      breakpointSm: 640,
      breakpointMd: 768,
      breakpointLg: 1024,
      breakpointXl: 1280,
      direction: 'ltr',
      datavizColor1: '#3b82f6',
      datavizColor2: '#ef4444',
      datavizColor3: '#10b981',
      datavizColor4: '#f97316',
      datavizColor5: '#8b5cf6',
      motion: 'full'
    },
    settings: { googleFonts: false, fontAwesome: false, animateCss: false, heroIcons: true }
  },
  {
    id: 'preset-vibrante',
    name: 'Vibrante (Rose)',
    tokens: {
      primary: '#f43f5e',
      background: '#ffffff',
      foreground: '#111827',
      secondary: '#f8fafc',
      accent: '#8b5cf6',
      muted: '#f3f4f6',
      destructive: '#b91c1c',
      border: '#e5e7eb',
      input: '#e5e7eb',
      ring: '#f43f5e',
      card: '#ffffff',
      cardForeground: '#111827',
      popover: '#ffffff',
      popoverForeground: '#111827',
      radius: 12,
      fontFamily: "'Inter', system-ui, sans-serif",
      fontSizeBase: 16,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
      spacing: 4,
      headerHeight: 56,
      sidebarWidth: 260,
      footerHeight: 48,
      breakpointSm: 640,
      breakpointMd: 768,
      breakpointLg: 1024,
      breakpointXl: 1280,
      direction: 'ltr',
      datavizColor1: '#3b82f6',
      datavizColor2: '#ef4444',
      datavizColor3: '#10b981',
      datavizColor4: '#f97316',
      datavizColor5: '#8b5cf6',
      motion: 'full'
    },
    settings: { googleFonts: true, fontAwesome: true, animateCss: true, heroIcons: true }
  },
  {
    id: 'preset-oscuro',
    name: 'Oscuro (Slate)',
    tokens: {
      primary: '#60a5fa',
      background: '#0f172a',
      foreground: '#e5e7eb',
      secondary: '#1f2937',
      accent: '#22d3ee',
      muted: '#334155',
      destructive: '#ef4444',
      border: '#334155',
      input: '#334155',
      ring: '#60a5fa',
      card: '#111827',
      cardForeground: '#e5e7eb',
      popover: '#111827',
      popoverForeground: '#e5e7eb',
      radius: 8,
      fontFamily: "'Inter', system-ui, sans-serif",
      fontSizeBase: 16,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
      spacing: 4,
      headerHeight: 56,
      sidebarWidth: 240,
      footerHeight: 48,
      breakpointSm: 640,
      breakpointMd: 768,
      breakpointLg: 1024,
      breakpointXl: 1280,
      direction: 'ltr',
      datavizColor1: '#3b82f6',
      datavizColor2: '#ef4444',
      datavizColor3: '#10b981',
      datavizColor4: '#f97316',
      datavizColor5: '#8b5cf6',
      motion: 'full'
    },
    settings: { googleFonts: true, fontAwesome: false, animateCss: false, heroIcons: true }
  },
  {
    id: 'preset-alto-contraste',
    name: 'Alto Contraste (Amber)',
    tokens: {
      primary: '#000000',
      background: '#ffffff',
      foreground: '#000000',
      secondary: '#000000',
      accent: '#ffcc00',
      muted: '#e5e7eb',
      destructive: '#ff0000',
      border: '#000000',
      input: '#000000',
      ring: '#000000',
      card: '#ffffff',
      cardForeground: '#000000',
      popover: '#ffffff',
      popoverForeground: '#000000',
      radius: 10,
      fontFamily: "'Inter', system-ui, sans-serif",
      fontSizeBase: 16,
      fontWeightRegular: 400,
      fontWeightMedium: 500,
      fontWeightBold: 700,
      spacing: 4,
      headerHeight: 56,
      sidebarWidth: 248,
      footerHeight: 48,
      breakpointSm: 640,
      breakpointMd: 768,
      breakpointLg: 1024,
      breakpointXl: 1280,
      direction: 'ltr',
      datavizColor1: '#3b82f6',
      datavizColor2: '#ef4444',
      datavizColor3: '#10b981',
      datavizColor4: '#f97316',
      datavizColor5: '#8b5cf6',
      motion: 'full'
    },
    settings: { googleFonts: false, fontAwesome: false, animateCss: false, heroIcons: false }
  }
];
