export enum ErrorCodes {
  UNKNOWN = 'ERR_UNKNOWN',
  VALIDATION = 'ERR_VALIDATION',
  AUTH_UNAUTHORIZED = 'ERR_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'ERR_FORBIDDEN',
  NOT_FOUND = 'ERR_NOT_FOUND',
  CONFLICT = 'ERR_CONFLICT',
  RATE_LIMIT = 'ERR_RATE_LIMIT',
  PAYLOAD_TOO_LARGE = 'ERR_PAYLOAD_TOO_LARGE',
  IDENTITY_DISABLED = 'ERR_IDENTITY_DISABLED',
  TENANT_REQUIRED = 'ERR_TENANT_REQUIRED',
  IDEMPOTENCY_KEY_REPLAY = 'ERR_IDEMPOTENT_REPLAY',
  WEBHOOK_DISABLED = 'ERR_WEBHOOK_DISABLED',
}
